
name: compile the overview
'on':
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Compile the Document
      run: |
        docker run --rm -v "$PWD:/work" -w /work -u "$(id -u):$(id -g)" texlive/texlive:latest \
          latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error "the-collection.tex"
    - name: Generate preview
      run: |
        sudo apt-get update && sudo apt-get install -y poppler-utils
        pdftoppm -png -f 1 -l 1 ./the-collection.pdf preview
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "the-collection.pdf" "preview-01.png"
        git commit -m "Newly compiled data"
    - name: Push changes
      run: git push --force origin HEAD:gh-pages
